"""Google Calendar integration with a headless OAuth2 flow (no browser popup).

The bot sends the user an authorization URL via Telegram. The user opens it,
grants access, and is redirected to a URL containing a `code` query parameter
(the page itself will fail to load, that is expected). The user sends that
code (or the whole URL) back to the bot, which exchanges it for a token.
"""
import os
from datetime import datetime, date, time, timedelta
from urllib.parse import urlparse, parse_qs
from zoneinfo import ZoneInfo

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from src.pdf_export import CATEGORY_GCAL_COLORS

SCOPES = ["https://www.googleapis.com/auth/calendar"]
CREDENTIALS_PATH = "credentials.json"
TOKEN_PATH = "token.json"
REDIRECT_URI = "http://localhost"
TIMEZONE = "Europe/Berlin"
CALENDAR_ID = "primary"

# Events created by the agent are tagged so we can safely clear/replan a week
# without touching the user's own appointments. The machine-readable tag in
# extendedProperties is the real safety gate; the marker is appended to the
# description so Djamal can also see at a glance which events are agent-created.
SOURCE_TAG = "life-os-agent"
AGENT_MARKER = "🤖 Life OS Agent"

DAY_OFFSETS = {
    "Montag": 0,
    "Dienstag": 1,
    "Mittwoch": 2,
    "Donnerstag": 3,
    "Freitag": 4,
    "Samstag": 5,
    "Sonntag": 6,
}
DAY_NAMES = list(DAY_OFFSETS.keys())

# PKCE code_verifier generated by get_auth_url(), needed again by exchange_code()
# to complete the same flow. Fine for a single-user bot/process.
_pending_code_verifier: str | None = None


class CalendarError(Exception):
    """Base class for all calendar errors."""


class CalendarNotConfiguredError(CalendarError):
    """Raised when credentials.json is missing."""


class CalendarNotConnectedError(CalendarError):
    """Raised when there is no valid token.json (OAuth not completed yet)."""


class CalendarAPIError(CalendarError):
    """Raised when a Google Calendar API call fails."""


# ── Authentication ──

def _load_credentials() -> Credentials | None:
    if not os.path.exists(TOKEN_PATH):
        return None

    creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)

    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
        except Exception as e:
            raise CalendarNotConnectedError(f"Token-Aktualisierung fehlgeschlagen: {e}") from e
        _save_credentials(creds)

    return creds


def _save_credentials(creds: Credentials) -> None:
    with open(TOKEN_PATH, "w") as f:
        f.write(creds.to_json())


def is_connected() -> bool:
    """Return True if a valid Google Calendar token is available."""
    try:
        creds = _load_credentials()
    except CalendarError:
        return False
    return creds is not None and creds.valid


def get_auth_url() -> str:
    """Build the Google OAuth consent URL the user must open in a browser."""
    if not os.path.exists(CREDENTIALS_PATH):
        raise CalendarNotConfiguredError(
            f"{CREDENTIALS_PATH} fehlt. Bitte OAuth-Client-Datei im Projektordner ablegen."
        )

    global _pending_code_verifier

    flow = Flow.from_client_secrets_file(CREDENTIALS_PATH, scopes=SCOPES, redirect_uri=REDIRECT_URI)
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent",
        include_granted_scopes="true",
    )
    _pending_code_verifier = flow.code_verifier
    return auth_url


def exchange_code(code_or_url: str) -> None:
    """Complete the OAuth flow using the code (or full redirect URL) the user sent back."""
    if not os.path.exists(CREDENTIALS_PATH):
        raise CalendarNotConfiguredError(
            f"{CREDENTIALS_PATH} fehlt. Bitte OAuth-Client-Datei im Projektordner ablegen."
        )

    code = code_or_url.strip()
    if code.startswith("http"):
        parsed = urlparse(code)
        params = parse_qs(parsed.query)
        if "code" not in params:
            raise CalendarAPIError("Die übergebene URL enthält keinen 'code'-Parameter.")
        code = params["code"][0]

    flow = Flow.from_client_secrets_file(
        CREDENTIALS_PATH, scopes=SCOPES, redirect_uri=REDIRECT_URI, code_verifier=_pending_code_verifier
    )
    try:
        flow.fetch_token(code=code)
    except Exception as e:
        raise CalendarAPIError(f"Token-Austausch fehlgeschlagen: {e}") from e

    _save_credentials(flow.credentials)


def _get_service():
    creds = _load_credentials()
    if creds is None or not creds.valid:
        raise CalendarNotConnectedError("Google Calendar ist nicht verbunden. Nutze /connect.")
    return build("calendar", "v3", credentials=creds)


# ── Reading events ──

def _parse_event(event: dict) -> dict:
    start = event["start"]
    end = event["end"]
    all_day = "date" in start

    if all_day:
        start_dt = datetime.fromisoformat(start["date"])
        end_dt = datetime.fromisoformat(end["date"])
    else:
        start_dt = datetime.fromisoformat(start["dateTime"])
        end_dt = datetime.fromisoformat(end["dateTime"])

    return {
        "id": event.get("id"),
        "summary": event.get("summary", "(Ohne Titel)"),
        "description": event.get("description", ""),
        "start": start_dt,
        "end": end_dt,
        "all_day": all_day,
        "is_agent": _raw_is_agent(event),
    }


def _raw_is_agent(event: dict) -> bool:
    """True if a raw Google event was created by this agent (carries our source tag)."""
    return event.get("extendedProperties", {}).get("private", {}).get("source") == SOURCE_TAG


def _get_events(time_min: datetime, time_max: datetime) -> list[dict]:
    service = _get_service()
    try:
        result = service.events().list(
            calendarId=CALENDAR_ID,
            timeMin=time_min.isoformat(),
            timeMax=time_max.isoformat(),
            singleEvents=True,
            orderBy="startTime",
        ).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Kalender konnte nicht gelesen werden: {e}") from e

    return [_parse_event(e) for e in result.get("items", [])]


def get_week_events(week_start: datetime) -> list[dict]:
    """Return all events between week_start (Monday) and the following Sunday (inclusive)."""
    tz = ZoneInfo(TIMEZONE)
    start = datetime.combine(week_start.date() if isinstance(week_start, datetime) else week_start, time.min, tzinfo=tz)
    end = start + timedelta(days=7)
    return _get_events(start, end)


def get_upcoming_events(days: int = 10) -> list[dict]:
    """Return all events from now until `days` days ahead."""
    tz = ZoneInfo(TIMEZONE)
    start = datetime.now(tz)
    end = start + timedelta(days=days)
    return _get_events(start, end)


def get_day_events(day: datetime) -> list[dict]:
    """Return all events for a single day."""
    tz = ZoneInfo(TIMEZONE)
    target_date = day.date() if isinstance(day, datetime) else day
    start = datetime.combine(target_date, time.min, tzinfo=tz)
    end = start + timedelta(days=1)
    return _get_events(start, end)


def format_events_summary(events: list[dict]) -> str:
    """Format events as a clean text summary, grouped by day (German), for LLM prompts or Telegram."""
    if not events:
        return "Keine bestehenden Termine."

    by_day: dict[date, list[dict]] = {}
    for event in events:
        day = event["start"].date()
        by_day.setdefault(day, []).append(event)

    lines = []
    for day in sorted(by_day.keys()):
        weekday = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"][day.weekday()]
        lines.append(f"{weekday}, {day.strftime('%d.%m.')}:")
        for event in by_day[day]:
            if event["all_day"]:
                lines.append(f"  - (ganztägig) {event['summary']}")
            else:
                start_str = event["start"].strftime("%H:%M")
                end_str = event["end"].strftime("%H:%M")
                lines.append(f"  - {start_str}-{end_str} {event['summary']}")

    return "\n".join(lines)


# ── Writing events ──

def create_event(title: str, date_: date, start_time: str, end_time: str, description: str = "", color_id: str | None = None) -> str:
    """Create a single calendar event. Times are 'HH:MM' strings. Returns the event id."""
    service = _get_service()
    tz = ZoneInfo(TIMEZONE)

    start_h, start_m = (int(p) for p in start_time.split(":"))
    end_h, end_m = (int(p) for p in end_time.split(":"))
    start_dt = datetime.combine(date_, time(start_h, start_m), tzinfo=tz)
    end_dt = datetime.combine(date_, time(end_h, end_m), tzinfo=tz)

    if end_dt <= start_dt:
        end_dt = start_dt + timedelta(hours=1)

    full_description = f"{description}\n\n{AGENT_MARKER}" if description else AGENT_MARKER

    body = {
        "summary": title,
        "description": full_description,
        "start": {"dateTime": start_dt.isoformat(), "timeZone": TIMEZONE},
        "end": {"dateTime": end_dt.isoformat(), "timeZone": TIMEZONE},
        "extendedProperties": {"private": {"source": SOURCE_TAG}},
    }
    if color_id:
        body["colorId"] = color_id

    try:
        created = service.events().insert(calendarId=CALENDAR_ID, body=body).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Termin konnte nicht erstellt werden: {e}") from e

    return created["id"]


# ── Single-event lookup, overlap check, safe update/delete ──

def _fetch_raw(service, event_id: str) -> dict:
    try:
        return service.events().get(calendarId=CALENDAR_ID, eventId=event_id).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Termin konnte nicht gefunden werden: {e}") from e


def get_event(event_id: str) -> dict:
    """Fetch and parse a single event by id."""
    service = _get_service()
    return _parse_event(_fetch_raw(service, event_id))


def find_overlaps(date_: date, start_time: str, end_time: str, exclude_event_id: str | None = None) -> list[dict]:
    """Return timed events on `date_` that overlap the [start_time, end_time) window.

    All-day events are ignored. Pass exclude_event_id to skip the event being moved.
    """
    tz = ZoneInfo(TIMEZONE)
    sh, sm = (int(p) for p in start_time.split(":"))
    eh, em = (int(p) for p in end_time.split(":"))
    start_dt = datetime.combine(date_, time(sh, sm), tzinfo=tz)
    end_dt = datetime.combine(date_, time(eh, em), tzinfo=tz)
    if end_dt <= start_dt:
        end_dt = start_dt + timedelta(hours=1)

    day_start = datetime.combine(date_, time.min, tzinfo=tz)
    day_end = day_start + timedelta(days=1)

    conflicts = []
    for ev in _get_events(day_start, day_end):
        if ev["all_day"] or ev["id"] == exclude_event_id:
            continue
        # Two intervals overlap iff each starts before the other ends.
        if start_dt < ev["end"] and ev["start"] < end_dt:
            conflicts.append(ev)
    return conflicts


def update_event(event_id: str, date_: date | None = None, start_time: str | None = None,
                 end_time: str | None = None, title: str | None = None) -> dict:
    """Move/reschedule an agent-created event. Refuses to touch events the agent did not create.

    Returns the updated parsed event. Raises CalendarError if the event is not agent-owned.
    """
    service = _get_service()
    raw = _fetch_raw(service, event_id)
    if not _raw_is_agent(raw):
        raise CalendarError(
            "Dieser Termin wurde nicht vom Life OS Agent erstellt und darf daher nicht geändert werden."
        )

    existing = _parse_event(raw)
    if existing["all_day"]:
        raise CalendarError("Ganztägige Termine können nicht verschoben werden.")

    tz = ZoneInfo(TIMEZONE)
    new_date = date_ or existing["start"].date()
    new_start = start_time or existing["start"].strftime("%H:%M")
    new_end = end_time or existing["end"].strftime("%H:%M")

    sh, sm = (int(p) for p in new_start.split(":"))
    eh, em = (int(p) for p in new_end.split(":"))
    start_dt = datetime.combine(new_date, time(sh, sm), tzinfo=tz)
    end_dt = datetime.combine(new_date, time(eh, em), tzinfo=tz)
    if end_dt <= start_dt:
        end_dt = start_dt + timedelta(hours=1)

    body = {
        "start": {"dateTime": start_dt.isoformat(), "timeZone": TIMEZONE},
        "end": {"dateTime": end_dt.isoformat(), "timeZone": TIMEZONE},
    }
    if title:
        body["summary"] = title

    try:
        updated = service.events().patch(calendarId=CALENDAR_ID, eventId=event_id, body=body).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Termin konnte nicht aktualisiert werden: {e}") from e

    return _parse_event(updated)


def delete_event(event_id: str) -> None:
    """Delete an agent-created event. Refuses to delete events the agent did not create."""
    service = _get_service()
    raw = _fetch_raw(service, event_id)
    if not _raw_is_agent(raw):
        raise CalendarError(
            "Dieser Termin wurde nicht vom Life OS Agent erstellt und darf daher nicht gelöscht werden."
        )

    try:
        service.events().delete(calendarId=CALENDAR_ID, eventId=event_id).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Termin konnte nicht gelöscht werden: {e}") from e


def create_week_plan(plan_dict: dict, week_start: date | None = None) -> list[dict]:
    """Create all events for a weekly plan.

    plan_dict maps German day names (Montag..Sonntag) to lists of
    {"time": "HH:MM - HH:MM", "title": str, "category": str} entries.
    Returns a list of {"day", "title", "event_id"} or {"day", "title", "error"}.
    """
    if week_start is None:
        today = datetime.now().date()
        week_start = today + timedelta(days=(7 - today.weekday()))
    elif isinstance(week_start, datetime):
        week_start = week_start.date()

    results = []
    for day_name, tasks in plan_dict.items():
        offset = DAY_OFFSETS.get(day_name)
        if offset is None:
            continue
        event_date = week_start + timedelta(days=offset)

        for task in tasks:
            title = task.get("title", "").strip()
            category = task.get("category", "")
            time_range = task.get("time", "")
            if not title:
                continue

            try:
                start_str, end_str = (part.strip() for part in time_range.split("-"))
                color_id = CATEGORY_GCAL_COLORS.get(category)
                event_id = create_event(title, event_date, start_str, end_str, description=category, color_id=color_id)
                results.append({"day": day_name, "title": title, "event_id": event_id})
            except (ValueError, CalendarError) as e:
                results.append({"day": day_name, "title": title, "error": str(e)})

    return results


def delete_week_events(week_start: datetime) -> int:
    """Delete all agent-created events (tagged with SOURCE_TAG) within the given week. Returns count deleted."""
    service = _get_service()
    tz = ZoneInfo(TIMEZONE)
    start = datetime.combine(week_start.date() if isinstance(week_start, datetime) else week_start, time.min, tzinfo=tz)
    end = start + timedelta(days=7)

    try:
        result = service.events().list(
            calendarId=CALENDAR_ID,
            timeMin=start.isoformat(),
            timeMax=end.isoformat(),
            singleEvents=True,
            privateExtendedProperty=f"source={SOURCE_TAG}",
        ).execute()

        events = result.get("items", [])
        for event in events:
            service.events().delete(calendarId=CALENDAR_ID, eventId=event["id"]).execute()
    except HttpError as e:
        raise CalendarAPIError(f"Termine konnten nicht gelöscht werden: {e}") from e

    return len(events)
